project:
  type: website
  output-dir: docs
  

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Nota** - Este es un reporte de demostración con un contraste ilustrativo"
    type: primary
    position: below-navbar
  
  page-footer: 
    left: "2024, Integrity Data" 
    # right: 
    #   - icon: github
    #     href: https://github.com/
    #   - icon: twitter 
    #     href: https://twitter.com/ 
  
  title: "Reporte RNAseq"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Inicio


format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

