project:
  type: website
  output-dir: docs
  

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Nota** - Esta es una versión interactiva del reporte NOMBRE_DEL_REPORTE.pdf"
    type: primary
    position: below-navbar
  
  page-footer: 
    left: "2024, Integrity Data" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
  
  title: "Reporte"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

